#!/bin/sh
# postrm script for mongodb

set -e

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    purge)
	# stop the service (if running), remove user and init script
	userdel mongodb
	rm /etc/init.d/mongodb
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
