#!/bin/sh
# prerm script for mongodb

set -e

echo "arg: $1"

case "$1" in
    remove|upgrade|deconfigure)
	# stop service if running
	service mongodb stop
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
